FROM orestisfl/env:latest
#ADD . /llvmPerturb
RUN apt-get install -qqy python-tqdm python-termcolor ipython time
#RUN cd llvmPerturb && cd /llvmPerturb/example_programs/wbs_aes_ches2016/src && gcc -Wall -Wextra *.c -o wb_reference
