all: src/nosuchcon_2013_whitebox_noenc_generator src/nosuchcon_2013_whitebox_noenc
nosuchcon_2013_whitebox_noenc_generator: src/nosuchcon_2013_whitebox_noenc_generator.c
	$(CC) $(CFLAGS) -o $@ $^
nosuchcon_2013_whitebox_noenc: src/nosuchcon_2013_whitebox_noenc.c
	$(CC) $(CFLAGS) -o $@ $^
